on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Archive
        uses: thedoctor0/zip-release@0.7.5
        with:
          type: "tar"
          filename: "code.tar.gz"
          command: "touch code.tar.gz"
          exclusions: "*.git* PKGBUILD code.tar.gz"
      - name: Upload
        uses: ncipollo/release-action@v1
        with:
          artifacts: "code.tar.gz"
          omitBody: true
